package casestudies.commonsmath4;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class IntervalcheckPoint3Suite0 {

  public static boolean debug = false;

  @Test
  public void test01() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test01"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.0d);

  }

  @Test
  public void test02() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test02"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test03() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test03"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test04() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test04"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.1d);

  }

  @Test
  public void test05() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test05"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.1d);

  }

  @Test
  public void test06() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test06"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test07() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test07"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.2d);

  }

  @Test
  public void test08() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test08"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.2d);

  }

  @Test
  public void test09() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test09"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.2d);

  }

  @Test
  public void test10() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test10"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test11() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test11"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test12() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test12"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test13() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test13"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test14() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test14"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test15() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test15"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test16() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test16"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test17() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test17"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test18() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test18"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test19() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test19"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test20() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test20"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test21() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test21"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test22() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test22"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test23() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test23"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test24() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test24"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test25() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test25"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test26() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test26"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test27() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test27"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test28() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test28"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test29() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test29"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test30() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test30"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test31() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test31"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test32() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test32"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test33() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test33"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test34() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test34"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test35() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test35"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test36() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test36"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test37() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test37"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test38() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test38"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test39() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test39"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test40() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test40"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test41() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test41"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test42() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test42"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test43() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test43"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test44() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test44"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test45() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test45"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test46() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test46"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test47() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test47"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test48() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test48"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test49() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test49"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test50() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test50"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test51() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test51"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test52() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test52"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test53() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test53"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test54() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test54"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test55() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test55"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test56() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test56"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test57() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test57"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test58() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test58"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test59() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test59"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test60() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test60"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test61() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test61"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test62() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test62"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test63() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test63"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test64() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test64"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test65() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test65"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test66() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test66"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test67() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test67"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.0d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == 0);

  }

  @Test
  public void test68() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test68"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.1d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == 0);

  }

  @Test
  public void test69() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test69"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.1d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

  @Test
  public void test70() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test70"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.2d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == 0);

  }

  @Test
  public void test71() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test71"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.2d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

  @Test
  public void test72() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint3Suite0.test72"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.2d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

}
